### PR TITLE
Carthage support

### LINKED ISSUE #16: Carthage support

### PR DESCRIPTION
**Pull request by tbaranes**
Close #16 

Carthage support, here we are 🎉

**Changes:**
- Migration to swift 3
- Delete the applications targets (with all the files corresponding)
- Creating shared framework (iOS and macOS) targets
- Drop the workspace, and pod dependencies (the xcodeproj is enough to compile and test the project)

**Missing / todo:**
- `InlineObjc`, I added the files used directly in the xcodeproj, but if you want to keep the dependance, the best way to do it would be to make it carthage compatible
- Updating travis to Xcode 8.1, and use the new targets to run the tests
- Fix the latest test (cf #18)

I tried as much as possible to keep your current architecture, but it's still a huge change 🤕 
For the next steps, let me know if you have any feedbacks, and if you are interested to merge that PR (despite of all these changes), otherwise, I will just keep using my fork

I tested the extract feature in my own app (iOS and macOS) using Carthage, it's working as expected!

### CODE REVIEW

**Comment by tbaranes** [comment]
@OlehKulykov Are interested in this? Adding Carthage support to your framework? I'm to rebase it, but since it's quite a work to do, I'd like to be sure that it will be merged in order to not work for nothing 😀

**Comment by OlehKulykov** [comment]
Hi, sorry for the long delay. Yes, I'm interesting in carthage support and merge will be available soon.
Thanks.

**Comment by tbaranes** [comment]
@OlehKulykov I take a quick look to the conflicts, it will be hard to rebase it, probably faster to restart. Before doing anything, I think a good move would be to upgrade the codebase to Swift 3, then cleaning the structure (adding a workspace, schemes...). Also, doing all of this in several PRs / steps in order to avoid conflicts if possible.

Let me know if I can help

**Comment by BHamrick1** [comment]
I would love this to work!

**Pull request closed without merging**
